spring:
  datasource:
    url: jdbc:h2:mem:marketplace
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console-marketplace
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: 'vendaEvent:br.com.zup.edu.commercemarketplace.marketplace.events.VendaEvent'
server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on-param
    include-binding-errors: always

logging:
  level:
    '[org.springframework.web.client]': DEBUG
    '[br.com.zup.edu.commercemarketplace.catalogoprodutos]': DEBUG
    '[br.com.zup.edu.commercemarketplace.consultausuarios]': DEBUG
    '[br.com.zup.edu.commercemarketplace.sistemapagamentos]': DEBUG
    '[org.springframework.orm.jpa]': DEBUG
    '[org.springframework.transaction]': DEBUG

feign:
  client:
    config:
      catalogoProdutos:
        loggerLevel: full
        decode404: true
      consultaUsuarios:
        loggerLevel: full
        decode404: true
      sistemaPagamentos:
        loggerLevel: full
